import { v4 as uuidv4 } from 'uuid';
import type {
  User,
  Workshop,
  WorkshopContext,
  AgendaBlock,
  Turma,
  Material,
  PostWorkshopFeedback,
  WorkshopTemplate,
} from './types';

// ============================================
// Dados de seed — DeckForge
// ============================================

const now = new Date().toISOString();

export const SEED_TEMPLATES: WorkshopTemplate[] = [
  {
    id: 'tpl-discovery',
    name: 'Discovery Workshop',
    description: 'Template completo para workshops de discovery com clientes. Inclui etapas de contexto, mapeamento de dores, ideação e priorização.',
    workshopType: 'discovery',
    estimatedDuration: 480,
    blocks: [
      { title: 'Check-in e Boas-vindas', description: 'Apresentação dos participantes e alinhamento de expectativas', objective: 'Criar conexão e alinhar expectativas', duration: 30, blockType: 'atividade', activityType: 'check_in', order: 0, materialIds: [] },
      { title: 'Contexto e Cenário Atual', description: 'Apresentação do cenário de negócio e desafios atuais', objective: 'Nivelar entendimento do contexto', duration: 60, blockType: 'atividade', activityType: 'apresentacao', order: 1, materialIds: [] },
      { title: 'Intervalo', description: 'Coffee break', objective: 'Pausa', duration: 15, blockType: 'pausa', activityType: 'break', order: 2, materialIds: [] },
      { title: 'Mapeamento de Dores e Oportunidades', description: 'Exercício colaborativo para mapear principais dores e oportunidades', objective: 'Identificar problemas e oportunidades', duration: 90, blockType: 'atividade', activityType: 'dinamica_grupo', order: 3, materialIds: [] },
      { title: 'Almoço', description: 'Pausa para almoço', objective: 'Pausa', duration: 60, blockType: 'pausa', activityType: 'break', order: 4, materialIds: [] },
      { title: 'Ideação de Soluções', description: 'Brainstorming estruturado para gerar ideias de solução', objective: 'Gerar ideias criativas', duration: 90, blockType: 'atividade', activityType: 'ideacao', order: 5, materialIds: [] },
      { title: 'Intervalo', description: 'Coffee break', objective: 'Pausa', duration: 15, blockType: 'pausa', activityType: 'break', order: 6, materialIds: [] },
      { title: 'Priorização e Roadmap', description: 'Priorização das ideias usando matriz de impacto x esforço', objective: 'Definir prioridades', duration: 60, blockType: 'atividade', activityType: 'priorizacao', order: 7, materialIds: [] },
      { title: 'Wrap-up e Próximos Passos', description: 'Consolidação dos resultados e definição de ações', objective: 'Alinhar próximos passos', duration: 30, blockType: 'wrap_up', activityType: 'wrap_up', order: 8, materialIds: [] },
    ],
    materials: [],
    createdBy: 'system',
    createdAt: now,
  },
  {
    id: 'tpl-ideacao',
    name: 'Workshop de Ideação',
    description: 'Template para sessões de brainstorming e ideação criativa. Ideal para gerar e refinar novas ideias de produto ou serviço.',
    workshopType: 'ideacao',
    estimatedDuration: 240,
    blocks: [
      { title: 'Abertura e Regras do Jogo', description: 'Apresentação da dinâmica e regras de brainstorming', objective: 'Definir regras de colaboração', duration: 20, blockType: 'atividade', activityType: 'check_in', order: 0, materialIds: [] },
      { title: 'Contexto do Desafio', description: 'Apresentação do desafio a ser resolvido', objective: 'Alinhar o desafio', duration: 30, blockType: 'atividade', activityType: 'apresentacao', order: 1, materialIds: [] },
      { title: 'Divergência: Brainstorming Livre', description: 'Sessão de geração livre de ideias (individual + grupo)', objective: 'Quantidade de ideias', duration: 60, blockType: 'atividade', activityType: 'ideacao', order: 2, materialIds: [] },
      { title: 'Intervalo', description: 'Coffee break', objective: 'Pausa', duration: 15, blockType: 'pausa', activityType: 'break', order: 3, materialIds: [] },
      { title: 'Convergência: Agrupamento e Votação', description: 'Agrupar ideias similares e votar nas mais promissoras', objective: 'Selecionar melhores ideias', duration: 45, blockType: 'atividade', activityType: 'priorizacao', order: 4, materialIds: [] },
      { title: 'Detalhamento das Top Ideias', description: 'Aprofundar as ideias selecionadas com canvas simplificado', objective: 'Detalhar ideias', duration: 45, blockType: 'atividade', activityType: 'dinamica_grupo', order: 5, materialIds: [] },
      { title: 'Fechamento e Compromissos', description: 'Definir responsáveis e prazos', objective: 'Garantir follow-up', duration: 25, blockType: 'wrap_up', activityType: 'wrap_up', order: 6, materialIds: [] },
    ],
    materials: [],
    createdBy: 'system',
    createdAt: now,
  },
  {
    id: 'tpl-retro',
    name: 'Retrospectiva de Sprint',
    description: 'Template para retrospectivas ágeis. Formato simples e eficaz para refletir sobre o que funcionou e o que pode melhorar.',
    workshopType: 'retrospectiva',
    estimatedDuration: 90,
    blocks: [
      { title: 'Check-in Rápido', description: 'Termômetro do time - como estamos chegando?', objective: 'Ler o clima do time', duration: 10, blockType: 'atividade', activityType: 'check_in', order: 0, materialIds: [] },
      { title: 'O que foi bem?', description: 'Pontos positivos da sprint', objective: 'Celebrar conquistas', duration: 20, blockType: 'atividade', activityType: 'discussao', order: 1, materialIds: [] },
      { title: 'O que pode melhorar?', description: 'Identificar pontos de melhoria', objective: 'Identificar problemas', duration: 20, blockType: 'atividade', activityType: 'discussao', order: 2, materialIds: [] },
      { title: 'Ações de melhoria', description: 'Definir ações concretas de melhoria', objective: 'Plano de ação', duration: 25, blockType: 'atividade', activityType: 'priorizacao', order: 3, materialIds: [] },
      { title: 'Check-out', description: 'Encerramento e agradecimentos', objective: 'Fechar sessão', duration: 10, blockType: 'wrap_up', activityType: 'wrap_up', order: 4, materialIds: [] },
    ],
    materials: [],
    createdBy: 'system',
    createdAt: now,
  },
  {
    id: 'tpl-kickoff',
    name: 'Kick-off de Projeto',
    description: 'Template para kick-offs de novos projetos. Alinha equipe, escopo, papéis e cronograma inicial.',
    workshopType: 'kickoff',
    estimatedDuration: 180,
    blocks: [
      { title: 'Boas-vindas e Apresentações', description: 'Apresentação do time e papéis', objective: 'Conhecer a equipe', duration: 20, blockType: 'atividade', activityType: 'check_in', order: 0, materialIds: [] },
      { title: 'Visão e Contexto do Projeto', description: 'Apresentação da visão, escopo e objetivos', objective: 'Alinhar visão', duration: 40, blockType: 'atividade', activityType: 'apresentacao', order: 1, materialIds: [] },
      { title: 'Intervalo', description: 'Coffee break', objective: 'Pausa', duration: 15, blockType: 'pausa', activityType: 'break', order: 2, materialIds: [] },
      { title: 'Papéis e Responsabilidades', description: 'RACI simplificado e definição de donos', objective: 'Definir responsabilidades', duration: 30, blockType: 'atividade', activityType: 'discussao', order: 3, materialIds: [] },
      { title: 'Cronograma e Milestones', description: 'Definição dos marcos e entregas principais', objective: 'Alinhar cronograma', duration: 30, blockType: 'atividade', activityType: 'discussao', order: 4, materialIds: [] },
      { title: 'Riscos e Dependências', description: 'Mapeamento rápido de riscos e dependências externas', objective: 'Identificar riscos', duration: 25, blockType: 'atividade', activityType: 'dinamica_grupo', order: 5, materialIds: [] },
      { title: 'Próximos Passos e Encerramento', description: 'Consolidação e definição das próximas ações', objective: 'Alinhar próximos passos', duration: 20, blockType: 'wrap_up', activityType: 'wrap_up', order: 6, materialIds: [] },
    ],
    materials: [],
    createdBy: 'system',
    createdAt: now,
  },
  {
    id: 'tpl-pitch-exec',
    name: 'Pitch Executivo',
    description: 'Template para apresentações executivas de alto impacto. Estrutura focada em problema-solução-valor para convencer stakeholders C-level em 30 minutos.',
    workshopType: 'pitch_executivo',
    estimatedDuration: 30,
    blocks: [
      { title: 'Abertura e Gancho', description: 'Dado ou história impactante que gere conexão imediata', objective: 'Capturar atenção', duration: 3, blockType: 'atividade', activityType: 'apresentacao', order: 0, materialIds: [] },
      { title: 'O Problema / Oportunidade', description: 'Contextualizar o desafio de negócio com dados concretos', objective: 'Gerar urgência', duration: 5, blockType: 'atividade', activityType: 'apresentacao', order: 1, materialIds: [] },
      { title: 'Solução Proposta', description: 'Apresentar a solução de forma clara e visual', objective: 'Demonstrar proposta de valor', duration: 8, blockType: 'atividade', activityType: 'apresentacao', order: 2, materialIds: [] },
      { title: 'Diferencial e Benefícios', description: 'Por que esta solução e por que agora', objective: 'Diferenciar da concorrência', duration: 5, blockType: 'atividade', activityType: 'apresentacao', order: 3, materialIds: [] },
      { title: 'Business Case / Números', description: 'ROI estimado, timeline e investimento', objective: 'Justificar financeiramente', duration: 5, blockType: 'atividade', activityType: 'apresentacao', order: 4, materialIds: [] },
      { title: 'Call to Action', description: 'Pedido claro e próximos passos definidos', objective: 'Converter decisão', duration: 4, blockType: 'wrap_up', activityType: 'wrap_up', order: 5, materialIds: [] },
    ],
    materials: [],
    createdBy: 'system',
    createdAt: now,
  },
  {
    id: 'tpl-treinamento-tech',
    name: 'Treinamento Técnico',
    description: 'Template para capacitação técnica de meio dia (4h). Combina teoria, demonstração prática e exercícios hands-on.',
    workshopType: 'treinamento_tecnico',
    estimatedDuration: 240,
    blocks: [
      { title: 'Boas-vindas e Agenda', description: 'Apresentação do programa e objetivos de aprendizagem', objective: 'Alinhar expectativas', duration: 15, blockType: 'atividade', activityType: 'check_in', order: 0, materialIds: [] },
      { title: 'Fundamentos Teóricos', description: 'Conceitos base com exemplos práticos', objective: 'Construir fundação teórica', duration: 45, blockType: 'atividade', activityType: 'apresentacao', order: 1, materialIds: [] },
      { title: 'Coffee Break', description: 'Intervalo', objective: 'Pausa', duration: 15, blockType: 'pausa', activityType: 'break', order: 2, materialIds: [] },
      { title: 'Demonstração Prática', description: 'Live demo do instrutor com passo-a-passo', objective: 'Mostrar aplicação real', duration: 45, blockType: 'atividade', activityType: 'apresentacao', order: 3, materialIds: [] },
      { title: 'Exercício Hands-on', description: 'Exercício prático individual ou em dupla', objective: 'Fixar aprendizado', duration: 60, blockType: 'atividade', activityType: 'dinamica_grupo', order: 4, materialIds: [] },
      { title: 'Coffee Break', description: 'Intervalo', objective: 'Pausa', duration: 15, blockType: 'pausa', activityType: 'break', order: 5, materialIds: [] },
      { title: 'Q&A e Troubleshooting', description: 'Dúvidas, problemas comuns e boas práticas', objective: 'Esclarecer dúvidas', duration: 25, blockType: 'atividade', activityType: 'discussao', order: 6, materialIds: [] },
      { title: 'Encerramento e Próximos Passos', description: 'Recursos adicionais, certificação e follow-up', objective: 'Garantir continuidade', duration: 20, blockType: 'wrap_up', activityType: 'wrap_up', order: 7, materialIds: [] },
    ],
    materials: [],
    createdBy: 'system',
    createdAt: now,
  },
  {
    id: 'tpl-proposta-com',
    name: 'Proposta Comercial',
    description: 'Template para apresentação estruturada de proposta comercial. Cobre empresa, solução, abordagem técnica, timeline e investimento.',
    workshopType: 'proposta_comercial',
    estimatedDuration: 60,
    blocks: [
      { title: 'Apresentação da Empresa', description: 'Quem somos, cases e credenciais relevantes', objective: 'Gerar credibilidade', duration: 10, blockType: 'atividade', activityType: 'apresentacao', order: 0, materialIds: [] },
      { title: 'Entendimento do Desafio', description: 'Demonstrar compreensão profunda do problema do cliente', objective: 'Validar entendimento', duration: 10, blockType: 'atividade', activityType: 'apresentacao', order: 1, materialIds: [] },
      { title: 'Solução Proposta', description: 'Visão geral da solução, funcionalidades-chave e valor', objective: 'Apresentar a solução', duration: 15, blockType: 'atividade', activityType: 'apresentacao', order: 2, materialIds: [] },
      { title: 'Arquitetura e Abordagem', description: 'Visão técnica, stack, metodologia e equipe', objective: 'Demonstrar expertise', duration: 10, blockType: 'atividade', activityType: 'apresentacao', order: 3, materialIds: [] },
      { title: 'Timeline e Investimento', description: 'Cronograma, fases, entregáveis e valores', objective: 'Alinhar expectativas', duration: 10, blockType: 'atividade', activityType: 'apresentacao', order: 4, materialIds: [] },
      { title: 'Próximos Passos', description: 'Q&A e definição dos próximos passos', objective: 'Avançar negociação', duration: 5, blockType: 'wrap_up', activityType: 'wrap_up', order: 5, materialIds: [] },
    ],
    materials: [],
    createdBy: 'system',
    createdAt: now,
  },
  {
    id: 'tpl-venda-consultiva',
    name: 'Venda Consultiva',
    description: 'Template para reunião de venda consultiva. Foco em entender necessidades, demonstrar valor e avançar oportunidade.',
    workshopType: 'venda_consultiva',
    estimatedDuration: 90,
    blocks: [
      { title: 'Quebra-gelo e Rapport', description: 'Conexão pessoal e contextualização da reunião', objective: 'Criar confiança', duration: 10, blockType: 'atividade', activityType: 'check_in', order: 0, materialIds: [] },
      { title: 'Levantamento de Necessidades', description: 'Perguntas estratégicas para entender dores e prioridades', objective: 'Mapear necessidades', duration: 20, blockType: 'atividade', activityType: 'discussao', order: 1, materialIds: [] },
      { title: 'Apresentação de Valor', description: 'Conectar capacidades com as necessidades identificadas', objective: 'Demonstrar fit', duration: 20, blockType: 'atividade', activityType: 'apresentacao', order: 2, materialIds: [] },
      { title: 'Demo ou Prova de Conceito', description: 'Demonstração prática adaptada ao contexto do cliente', objective: 'Tangibilizar a solução', duration: 20, blockType: 'atividade', activityType: 'apresentacao', order: 3, materialIds: [] },
      { title: 'Objeções e Negociação', description: 'Endereçar preocupações e alinhar expectativas', objective: 'Superar objeções', duration: 10, blockType: 'atividade', activityType: 'discussao', order: 4, materialIds: [] },
      { title: 'Fechamento e Próximos Passos', description: 'Confirmar interesse e definir ações concretas', objective: 'Avançar pipeline', duration: 10, blockType: 'wrap_up', activityType: 'wrap_up', order: 5, materialIds: [] },
    ],
    materials: [],
    createdBy: 'system',
    createdAt: now,
  },
  {
    id: 'tpl-onboarding',
    name: 'Onboarding de Equipe',
    description: 'Template para sessão de onboarding de novos membros. Cobre cultura, processos, ferramentas e integração com o time.',
    workshopType: 'onboarding',
    estimatedDuration: 180,
    blocks: [
      { title: 'Boas-vindas e Cultura', description: 'Apresentação da empresa, valores e cultura organizacional', objective: 'Acolher e conectar', duration: 20, blockType: 'atividade', activityType: 'apresentacao', order: 0, materialIds: [] },
      { title: 'Estrutura e Processos', description: 'Organograma, fluxos de trabalho e rituais do time', objective: 'Entender funcionamento', duration: 30, blockType: 'atividade', activityType: 'apresentacao', order: 1, materialIds: [] },
      { title: 'Ferramentas e Acessos', description: 'Setup de ambiente, ferramentas e permissões necessárias', objective: 'Habilitar produtividade', duration: 30, blockType: 'atividade', activityType: 'apresentacao', order: 2, materialIds: [] },
      { title: 'Coffee Break', description: 'Intervalo e networking informal', objective: 'Pausa', duration: 15, blockType: 'pausa', activityType: 'break', order: 3, materialIds: [] },
      { title: 'Conhecendo o Produto/Serviço', description: 'Deep dive no produto, arquitetura e roadmap', objective: 'Entender o que fazemos', duration: 45, blockType: 'atividade', activityType: 'apresentacao', order: 4, materialIds: [] },
      { title: 'Dinâmica de Integração', description: 'Atividade lúdica para conhecer colegas e descontrair', objective: 'Integrar ao time', duration: 25, blockType: 'atividade', activityType: 'dinamica_grupo', order: 5, materialIds: [] },
      { title: 'Dúvidas e Encerramento', description: 'Espaço aberto para perguntas e definição de buddy/mentor', objective: 'Esclarecer e acolher', duration: 15, blockType: 'wrap_up', activityType: 'wrap_up', order: 6, materialIds: [] },
    ],
    materials: [],
    createdBy: 'system',
    createdAt: now,
  },
];

export const SEED_WORKSHOPS: Workshop[] = [
  {
    id: 'ws-001',
    title: 'Discovery Workshop - Plataforma de Seguros',
    type: 'discovery',
    clientArea: 'Acme Insurance',
    targetDate: '2026-04-15',
    estimatedDuration: 480,
    location: 'presencial',
    status: 'em_preparacao',
    ownerId: 'user-001',
    coFacilitators: [],
    isTemplate: false,
    templateId: 'tpl-discovery',
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-03-18T14:30:00Z',
  },
  {
    id: 'ws-002',
    title: 'Ideação: Novo App Mobile B2C',
    type: 'ideacao',
    clientArea: 'TechCorp Digital',
    targetDate: '2026-04-22',
    estimatedDuration: 240,
    location: 'online',
    status: 'rascunho',
    ownerId: 'user-001',
    coFacilitators: ['user-002'],
    isTemplate: false,
    createdAt: '2026-03-15T09:00:00Z',
    updatedAt: '2026-03-15T09:00:00Z',
  },
  {
    id: 'ws-003',
    title: 'Retrospectiva Q1 - Time Alpha',
    type: 'retrospectiva',
    clientArea: 'Interno - Time Alpha',
    targetDate: '2026-03-28',
    estimatedDuration: 90,
    location: 'online',
    status: 'agenda_aprovada',
    ownerId: 'user-001',
    coFacilitators: [],
    isTemplate: false,
    templateId: 'tpl-retro',
    createdAt: '2026-03-12T11:00:00Z',
    updatedAt: '2026-03-19T16:00:00Z',
  },
  {
    id: 'ws-004',
    title: 'Pitch Executivo - Plataforma de IA Generativa',
    type: 'pitch_executivo',
    clientArea: 'Board Executivo - TechCorp',
    targetDate: '2026-04-10',
    estimatedDuration: 30,
    location: 'presencial',
    status: 'em_preparacao',
    ownerId: 'user-001',
    coFacilitators: [],
    isTemplate: false,
    templateId: 'tpl-pitch-exec',
    createdAt: '2026-03-16T14:00:00Z',
    updatedAt: '2026-03-19T10:00:00Z',
  },
  {
    id: 'ws-005',
    title: 'Treinamento: Fundamentos de Cloud Azure',
    type: 'treinamento_tecnico',
    clientArea: 'Equipe Dev - CloudFirst',
    targetDate: '2026-05-05',
    estimatedDuration: 240,
    location: 'hibrido',
    status: 'rascunho',
    ownerId: 'user-001',
    coFacilitators: [],
    isTemplate: false,
    templateId: 'tpl-treinamento-tech',
    createdAt: '2026-03-18T09:00:00Z',
    updatedAt: '2026-03-18T09:00:00Z',
  },
];

export const SEED_TURMAS: Turma[] = [
  {
    id: 'turma-001',
    workshopId: 'ws-001',
    name: 'Turma 1 - São Paulo',
    date: '2026-04-15',
    time: '09:00',
    duration: 480,
    locationType: 'presencial',
    locationValue: 'Av. Paulista, 1000 - Sala 801',
    facilitatorId: 'user-001',
    status: 'em_preparacao',
    customAgenda: false,
    materialIds: ['mat-001', 'mat-002'],
    createdAt: '2026-03-10T10:30:00Z',
    updatedAt: '2026-03-18T14:30:00Z',
  },
  {
    id: 'turma-002',
    workshopId: 'ws-001',
    name: 'Turma 2 - Rio de Janeiro',
    date: '2026-04-22',
    time: '09:00',
    duration: 480,
    locationType: 'presencial',
    locationValue: 'Rua do Ouvidor, 50 - Sala 302',
    facilitatorId: 'user-001',
    status: 'rascunho',
    customAgenda: false,
    materialIds: ['mat-001'],
    createdAt: '2026-03-12T11:00:00Z',
    updatedAt: '2026-03-12T11:00:00Z',
  },
  {
    id: 'turma-003',
    workshopId: 'ws-003',
    name: 'Sessão Única - Online',
    date: '2026-03-28',
    time: '14:00',
    duration: 90,
    locationType: 'online',
    locationValue: 'https://teams.microsoft.com/l/meetup-join/xxx',
    facilitatorId: 'user-001',
    status: 'pronta',
    customAgenda: false,
    materialIds: [],
    createdAt: '2026-03-12T11:30:00Z',
    updatedAt: '2026-03-19T16:00:00Z',
  },
];

export const SEED_BLOCKS: AgendaBlock[] = [
  { id: 'blk-001', workshopId: 'ws-001', title: 'Check-in e Boas-vindas', description: 'Apresentação dos participantes e alinhamento de expectativas', objective: 'Criar conexão', duration: 30, blockType: 'atividade', activityType: 'check_in', order: 0, materialIds: [] },
  { id: 'blk-002', workshopId: 'ws-001', title: 'Contexto e Cenário Atual', description: 'Apresentação do cenário de negócio', objective: 'Nivelar entendimento', duration: 60, blockType: 'atividade', activityType: 'apresentacao', order: 1, materialIds: ['mat-001'] },
  { id: 'blk-003', workshopId: 'ws-001', title: 'Coffee Break', description: 'Intervalo', objective: 'Pausa', duration: 15, blockType: 'pausa', activityType: 'break', order: 2, materialIds: [] },
  { id: 'blk-004', workshopId: 'ws-001', title: 'Mapeamento de Dores', description: 'Exercício colaborativo para mapear dores', objective: 'Identificar problemas', duration: 90, blockType: 'atividade', activityType: 'dinamica_grupo', order: 3, materialIds: ['mat-002'] },
  { id: 'blk-005', workshopId: 'ws-001', title: 'Almoço', description: 'Pausa para almoço', objective: 'Pausa', duration: 60, blockType: 'pausa', activityType: 'break', order: 4, materialIds: [] },
  { id: 'blk-006', workshopId: 'ws-001', title: 'Ideação de Soluções', description: 'Brainstorming estruturado', objective: 'Gerar ideias', duration: 90, blockType: 'atividade', activityType: 'ideacao', order: 5, materialIds: [] },
  { id: 'blk-007', workshopId: 'ws-001', title: 'Priorização', description: 'Matriz impacto x esforço', objective: 'Definir prioridades', duration: 60, blockType: 'atividade', activityType: 'priorizacao', order: 6, materialIds: [] },
  { id: 'blk-008', workshopId: 'ws-001', title: 'Wrap-up', description: 'Consolidação e próximos passos', objective: 'Fechar sessão', duration: 30, blockType: 'wrap_up', activityType: 'wrap_up', order: 7, materialIds: [] },
  { id: 'blk-009', workshopId: 'ws-004', title: 'Abertura e Gancho', description: 'Dado impactante que gere conexão', objective: 'Capturar atenção', duration: 3, blockType: 'atividade', activityType: 'apresentacao', order: 0, materialIds: [] },
  { id: 'blk-010', workshopId: 'ws-004', title: 'O Problema / Oportunidade', description: 'Contextualizar o desafio com dados', objective: 'Gerar urgência', duration: 5, blockType: 'atividade', activityType: 'apresentacao', order: 1, materialIds: [] },
  { id: 'blk-011', workshopId: 'ws-004', title: 'Solução Proposta', description: 'Apresentação clara e visual da solução', objective: 'Demonstrar valor', duration: 8, blockType: 'atividade', activityType: 'apresentacao', order: 2, materialIds: [] },
  { id: 'blk-012', workshopId: 'ws-004', title: 'Diferencial e Benefícios', description: 'Por que esta solução e por que agora', objective: 'Diferenciar', duration: 5, blockType: 'atividade', activityType: 'apresentacao', order: 3, materialIds: [] },
  { id: 'blk-013', workshopId: 'ws-004', title: 'Business Case', description: 'ROI, timeline e investimento', objective: 'Justificar', duration: 5, blockType: 'atividade', activityType: 'apresentacao', order: 4, materialIds: [] },
  { id: 'blk-014', workshopId: 'ws-004', title: 'Call to Action', description: 'Pedido claro e próximos passos', objective: 'Converter', duration: 4, blockType: 'wrap_up', activityType: 'wrap_up', order: 5, materialIds: [] },
];

export const SEED_MATERIALS: Material[] = [
  {
    id: 'mat-001',
    workshopId: 'ws-001',
    name: 'Deck de Contexto - Acme Insurance',
    type: 'link',
    phase: 'durante',
    url: 'https://docs.google.com/presentation/d/abc123',
    applyToAll: true,
    turmaIds: [],
    createdAt: '2026-03-10T11:00:00Z',
  },
  {
    id: 'mat-002',
    workshopId: 'ws-001',
    name: 'Board Miro - Mapeamento de Dores',
    type: 'link',
    phase: 'durante',
    url: 'https://miro.com/app/board/xxx',
    applyToAll: true,
    turmaIds: [],
    createdAt: '2026-03-10T11:15:00Z',
  },
  {
    id: 'mat-003',
    workshopId: 'ws-001',
    name: 'Pesquisa Prévia - Resultados NPS',
    type: 'arquivo',
    phase: 'pre_workshop',
    fileName: 'resultados-nps-q4.pdf',
    fileSize: 2048000,
    applyToAll: false,
    turmaIds: ['turma-001'],
    createdAt: '2026-03-14T10:00:00Z',
  },
];

export const SEED_CONTEXTS: WorkshopContext[] = [
  {
    id: 'ctx-001',
    workshopId: 'ws-001',
    businessProblem: 'O cliente Acme Insurance enfrenta alta taxa de cancelamento de apólices (churn de 25% a.a.) e precisa entender as dores dos segurados para redesenhar a jornada digital.',
    mainObjective: 'Mapear dores dos segurados e identificar oportunidades de melhoria na jornada digital de seguros.',
    expectedOutputs: ['Mapa de dores priorizado', 'Lista de oportunidades de melhoria', 'Roadmap inicial de ações'],
    participantProfiles: ['executivos', 'pms', 'designers'],
    maturityLevel: 'medio',
    additionalNotes: 'O diretor de produto estará presente apenas na abertura e fechamento. Garantir que o wrap-up seja apresentável para C-level.',
  },
];

export const SEED_USER: User = {
  id: 'user-001',
  name: 'Ana Costa',
  email: 'ana.costa@empresa.com',
  role: 'facilitador',
  createdAt: now,
  updatedAt: now,
};
